// <auto-generated />
using System;
using Lanche_Bom.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lanche_Bom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221021184630_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ItemPedidoPedido", b =>
                {
                    b.Property<int>("ItensPedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItensPedidoId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItensPedidoId", "ItensPedidoId1");

                    b.HasIndex("ItensPedidoId1");

                    b.ToTable("ItemPedidoPedido");
                });

            modelBuilder.Entity("Lanche_Bom.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("Lanche_Bom.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalPagar")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ItemPedidoPedido", b =>
                {
                    b.HasOne("Lanche_Bom.Models.ItemPedido", null)
                        .WithMany()
                        .HasForeignKey("ItensPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lanche_Bom.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("ItensPedidoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
